[features]
resolution = true
skip-lint = false

[programs.devnet]
zk_poop_staking = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.localnet]
zk_poop_staking = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/*"
]

[[test.validator.account]]
address = "11111111111111111111111111111111"
program_id = "11111111111111111111111111111111"

[build]
dockerfile = "Dockerfile"

[toolchain]
anchor_version = "0.31.1"

[provider.cluster]
devnet = "https://lb.drpc.org/solana-devnet/Aqfm2hO8SEtdr3WkOHEz8w32Snnab04R8LTeEklbR4ac"
mainnet = "https://lb.drpc.org/ogrpc/mainnet-beta/Aqfm2hO8SEtdr3WkOHEz8w32Snnab04R8LTeEklbR4ac"